### ISSUE TITLE
Type parameter in more events

### ISSUE THREAD

**Issue by jacobo221** [pdf/kodi-callback-daemon#2]
Hi,

This project is great!

It is better than service.xbmc.callbacks in that you can filter events based on the type of media (movie, episode, music).

However after testing and looking into the code this filter only works with OnPlay. I would love it to work also with OnStop and OnPause. The reason being that I could dim/bright the lights only when watching films/episodes, not when listening to music (which I do both to sleep, lights off, and to have dinner, lights on). Currently lights go bright when the music playlist finishes, so I can't keep sleeping on the sofa hehe

I checked the Kodi API ( http://kodi.wiki/view/JSON-RPC_API/v6 ) and it looks like this is possible.

Could this feature be added please? :)

Thanks and keeo up this great work!

**Comment by pdf** [comment]
Should be live in [v1.2.0](https://github.com/pdf/kodi-callback-daemon/releases/tag/v1.2.0), though I haven't tested that it actually works.
